### ISSUE TITLE
Parser can't handle (this=*that*)

### ISSUE THREAD

**Issue by alfmel** [tapmodo/node-ldap-filters#1]
Thanks for the great library. It helped my project tremendously.

Just an FYI. I tried to parse an LDAP filter that had (this=_that_) and it failed. The reason is that the =\* operator doesn't expect data after it. I fixed it at my end by removing the EQ_STAR and "present" code from parser.jison. That solution worked for me but may not work for others. That's why I'm not submitting a pull request.

**Comment by tapmodo** [comment]
Thanks for writing, and I'm glad you found the library helpful! I've tested it and I see the parse error that is generated. I'm working on a fix.

**Comment by tapmodo** [comment]
I wrote an additional test and fortified the presense match test, and it looks like your solution doesn't break anything. The present() method is just a shorthand to create a filter with a comparison operator of _equals_ and a value of `*`, so it did not need to be specially parsed.

I published a patch to NPM and github.  
Good catch! Thanks again!!

**Comment by alfmel** [comment]
Wow! Thanks for the quick response to the issue. I'm glad my solution worked and that you were OK with it. Again, thanks for the fast fix.
